version: '2'

services:
  web:
    restart: always
    build: ./web
    ports:
      - "8000:8000"
    command: ./run_web.sh
    links:
      - redis
    depends_on:
      - postgres

  postgres:
    restart: always
    build: ./postgresql
    ports:
      - "5432:5432"

  redis:
    restart: always
    image: redis
    expose:
       - "6379"

  celery_worker:
    build: ./web
    command: ./run_celery_worker.sh
    user: nobody
    links:
      - postgres
      - redis
    depends_on:
      - web

  celery_beat:
    build: ./web
    command: ./run_celery_beat.sh
    links:
      - postgres
      - redis
    depends_on:
      - web